force-app/main/default/objects/Additive__c/Additive__c.object-meta.xml
<CustomObject>
    <label>Additive</label>
    <nameField>
        <label>Additive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pancake__c/Pancake__c.object-meta.xml
<CustomObject>
    <label>Pancake</label>
    <nameField>
        <label>Pancake</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pancakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pancake__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <summarizedField>Pancake_Additive__c.Price__c</summarizedField>
    <summaryForeignKey>Pancake_Additive__c.Pancake__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Pancake_Additive__c/Pancake_Additive__c.object-meta.xml
<CustomObject>
    <label>Pancake_Additive</label>
    <nameField>
        <displayFormat>Pancake_Additive-{0000}</displayFormat>
        <label>Pancake_Additive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pancake_Additives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pancake_Additive__c/fields/Additive__c.field-meta.xml
<CustomField>
    <fullName>Additive__c</fullName>
    <label>Additive</label>
    <referenceTo>Additive__c</referenceTo>
    <relationshipLabel>Pancake_Additives</relationshipLabel>
    <relationshipName>Pancake_Additives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pancake_Additive__c/fields/Pancake__c.field-meta.xml
<CustomField>
    <fullName>Pancake__c</fullName>
    <label>Pancake</label>
    <referenceTo>Pancake__c</referenceTo>
    <relationshipLabel>Pancake_Additives</relationshipLabel>
    <relationshipName>Pancake_Additives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PriceTransfer_Test.cls
@isTest
public class PriceTransfer_Test {

    @testSetup
    static void setup() {
        Pancake__c pancakeForAdditives = new Pancake__c(Name = 'Test Pancake');
        insert pancakeForAdditives;
        List<Additive__c> additives = new List<Additive__c>();
        List<Pancake_Additive__c> pancakeAdditives = new List<Pancake_Additive__c>();

        for(Integer i=0; i < 200; i++) {
            Additive__c additive = new Additive__c(
                Name='Test additive' + i,
                Price__c = 1
            );
            additives.add(additive);
        }
        insert additives;
        for(Additive__c additive : additives){
            Pancake_Additive__c pancakeAdditive = new Pancake_Additive__c(
                Pancake__c = pancakeForAdditives.Id,
                Additive__c = additive.Id,
                Price__c = 0
            );
            pancakeAdditives.add(pancakeAdditive);
        }
        insert pancakeAdditives;
    }

    @isTest static void TestAdditivePriceToChange(){
        List<Additive__c> selectAdditives = [SELECT Name, Price__c FROM Additive__c WHERE Name Like 'Test additive%'];

        for(Additive__c additive : selectAdditives){
            //change Price for additives
            additive.Price__c = 9.99;
        }
        update selectAdditives;
        //check related list
        List<Pancake_Additive__c> pancakeAdditivesCheck = [SELECT Additive__c, Price__c
                                                           FROM Pancake_Additive__c
                                                           WHERE Additive__c IN :selectAdditives
                                                          ];
        System.assertEquals(200, pancakeAdditivesCheck.size());
        //check related Price field
        List<Pancake_Additive__c> pancakeAdditivesCheckPrice = [SELECT Price__c
                                                                FROM Pancake_Additive__c
                                                               ];
        System.assertEquals(9.99, pancakeAdditivesCheckPrice[0].Price__c);

    }
}